### ISSUE TITLE
作者你好请教个问题

### ISSUE THREAD

**Issue by mbg17** [zhuxiujia/GoMybatisMall#2]
UpdateBy   string    `json:"updateBy"` 我结构体这么写为啥映射不上，我看mybatis的是可以映射上的

**Comment by mbg17** [comment]
一定要严格按照update_time这种格式写吗？

**Comment by zhuxiujia** [comment]
是的  必须含有time才会识别成功吧

**Comment by mbg17** [comment]
哦哦，我也看出来了，xml的column是根据tag映射的
